export enum Modal {
	NONE = "NONE",
	SAVEERROR = "SAVEERROR",
	CONTACTUS = "CONTACTUS",
	DELETELIST = "DELETELIST",
	DELETECHARACTER = "DELETECHARACTER",
	NEWIMAGE = "NEWIMAGE",
	LOADCOLLECTION = "LOADCOLLECTION",
	IMPORTLIST = "IMPORTLIST",
	NEWLIST = "NEWLIST",
	FULLSCREENIMG = "FULLSCREENIMG",
	TUTORIAL = "TUTORIAL",
}
